# Generated by Django 5.2.9 on 2026-06-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_cart_cartitem_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="title",
            new_name="name",
        ),
    ]
