# Generated by Django 5.2.9 on 2026-06-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_slug_hash_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug_hash",
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
