# Generated by Django 5.2.9 on 2026-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_customer_options_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
    ]
