# Generated by Django 5.2.9 on 2026-01-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_customer_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
