# Generated by Django 5.2.9 on 2026-02-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
