# Generated by Django 5.2.9 on 2026-03-14 18:22

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images/", validators=[store.validators.validate]
            ),
        ),
    ]
