# Generated by Django 5.2.9 on 2026-06-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
    ]
