# Generated by Django 5.2.9 on 2026-06-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_title_collection_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug_hash",
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=500),
        ),
    ]
