# Generated by Django 5.2.9 on 2026-06-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.customer",
            ),
            preserve_default=False,
        ),
    ]
